INSERT INTO `ps_product` (`id_product`, `id_supplier`, `id_manufacturer`, `id_category_default`, `id_shop_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ean13`, `isbn`, `upc`, `mpn`, `ecotax`, `quantity`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price`, `unit_price_ratio`, `additional_shipping_cost`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `out_of_stock`, `additional_delivery_times`, `quantity_discount`, `customizable`, `uploadable_files`, `text_fields`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `cache_default_attribute`, `date_add`, `date_upd`, `advanced_stock_management`, `pack_stock_type`, `state`, `product_type`) VALUES
({product_id}, 0, 0, 2, 1, {tax_rules_group_id}, 0, 1, '', '', '', '', 0.000000, 0, 1, 0, 0, {price}, 0.000000, '', 0.000000, 0.000000, 0.000000, '{reference}', '', '', 0.000000, 0.000000, 0.000000, 0.000000, 2, 1, 0, 0, 0, 0, 0, 'default', 0, 1, '0000-00-00', 0, 'new', 1, 0, 'none', 0, 0, 1, 0, '2025-09-26 10:06:09', '2025-09-26 10:25:57', 0, 3, 1, 'virtual');

INSERT INTO `ps_product_lang` (`id_product`, `id_shop`, `id_lang`, `description`, `description_short`, `link_rewrite`, `meta_description`, `meta_keywords`, `meta_title`, `name`, `available_now`, `available_later`, `delivery_in_stock`, `delivery_out_stock`) VALUES
({product_id}, 1, {lang_id}, '<p>I PFU, acronimo di Pneumatici Fuori Uso, sono gli pneumatici che non sono più utilizzabili sui veicoli e non vengono più rigenerati o riutilizzati.</p>\n<p> Questi rifiuti, generati dalla dismissione di pneumatici da auto, moto o mezzi pesanti, sono costituiti da gomma, acciaio e fibre tessili, materiali che possono essere recuperati e riutilizzati in diversi settori.</p>\n<p> In Italia, il contributo PFU è obbligatorio e viene applicato al momento dell\'acquisto di pneumatici nuovi o di veicoli nuovi con pneumatici già installati, coprendo i costi futuri dello smaltimento.</p>\n<p> Il contributo è prepagato e viene versato a consorzi come Ecopneus ed Ecotyre, che gestiscono la raccolta, il trasporto e il trattamento dei PFU per il riciclo o il recupero energetico.</p>', '<p>Contributo Ambientale FPU</p>', 'fpu-500-eur', '', '', '', 'FPU 5.00 EUR', '', '', '', '');

INSERT INTO `ps_product_shop` (`id_product`, `id_shop`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `uploadable_files`, `text_fields`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES
({product_id}, 1, 2, {tax_rules_group_id}, 0, 1, 0.000000, 1, 0, 0, {price}, 0.000000, '', 0.000000, 0.000000, 0.000000, 0, 0, 0, 0, 'default', 0, 1, '0000-00-00', 0, 'new', 1, 0, 'none', 0, 0, '2025-09-26 10:06:09', '2025-09-26 10:25:57', 3);

